### ISSUE TITLE
HUMANN_RUN_SAMPLE_TSV  tsv generation

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#1]
J'ai oublié de te demander : est-ce que tu pourrais nous écrire une petite commande pour générer ce fichier? ex. avec les samples boreal_moss je faisais des manips de strings pour arriver à isoler une partie du nom. C'est du cas-par-cas, mais si j'avais au moins une bride de code pour créer ces deux column à partir de ma liste de samples ça serait génial!

**Comment by jflucier** [comment]
tu veux dire extraction de sample name a partir des nom de fastq?

**Comment by jorondo1** [comment]
exact; le string manip va être différent pour chaque projet, mais si j'ai au moins le code pour créer le fichier à 2 columns ça aiderait ?

**Comment by jorondo1** [comment]
good to know, j'aurais été du genre à passer trop de temps à trouver comment faire ça avec awk 🙃

**Comment by jorondo1** [comment]
peux-tu me dire si /ip29/ilafores_group/sarahi/boreal_moss/custom_pipeline/CUSTOM_DB_SAMPLE.tsv te semble adéquat pour starter ?

**Comment by jflucier** [comment]
semble avoir des eol bizarre... faut que ce soit eol linux.

en fait ca l'air plus d'un log....

`
[ronj2303@ip29-mp2 ~]$ less  /ip29/ilafores_group/sarahi/boreal_moss/custom_pipeline/CUSTOM_DB_SAMPLE.tsv
N-1-DICUND-B    /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_11---IDT_i5_11.N-1-DICUND-B_R1.fastq.gz      /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_11---IDT_i5_11.N-1-DICUND-B_R2.fastq.gz**^M**N-1-DICUND-G        /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_22---IDT_i5_22.N-1-DICUND-G_R1.fastq.gz      /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_22---IDT_i5_22.N-1-DICUND-G_R2.fastq.gz^MN-1-POLCOM-G        /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_18---IDT_i5_18.N-1-POLCOM-G_R1.fastq.gz      /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_18---IDT_i5_18.N-1-POLCOM-G_R2.fastq.gz^MN-1-POLJUN-B        /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_48---IDT_i5_48.N-1-POLJUN-B_R1.fastq.gz      /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_48---IDT_i5_48.N-1-POLJUN-B_R2.fastq.gz^MN-1-POLJUN-G        /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_33---IDT_i5_33.N-1-POLJUN-G_R1.fastq.gz      /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_33---IDT_i5_33.N-1-POLJUN-G_R2.fastq.gz**^M**N-1-POLPIL-G        /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_39---IDT_i5_39.N-1-POLPIL-G_R1.fastq.gz      /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_39---IDT_i5_39.N-1-POLPIL-G_R2.fastq.gz^MN-1-RACCAN-G        /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_30---IDT_i5_30.N-1-RACCAN-G_R1.fastq.gz      /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_30---IDT_i5_30.N-1-RACCAN-G_R2.fastq.gz^MN-1-TORTORT-G       /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_45---IDT_i5_45.N-1-TORTORT-G_R1.fastq.gz     /ip29/ilafores_group/sarahi/bore/ip29/ilafores_group/sarahi/boreal_moss/custom_pipeline/CUSTOM_DB_SAMPLE.tsv...skipping...
N-1-DICUND-B    /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_11---IDT_i5_11.N-1-DICUND-B_R1.fastq.gz      /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_11---IDT_i5_11.N-1-DICUND-B_R2.fastq.gz^MN-1-DICUND-G        /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_22---IDT_i5_22.N-1-DICUND-G_R1.fastq.gz      /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_22---IDT_i5_22.N-1-DICUND-G_R2.fastq.gz^MN-1-POLCOM-G        /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_18---IDT_i5_18.N-1-POLCOM-G_R1.fastq.gz      /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_18---IDT_i5_18.N-1-POLCOM-G_R2.fastq.gz^MN-1-POLJUN-B        /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_48---IDT_i5_48.N-1-POLJUN-B_R1.fastq.gz
      /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_48---IDT_i5_48.N-1-POLJUN-B_R2.fastq.gz^MN-1-POLJUN-G        /ip29/ilafores_group/sarahi/boreal_moss_samples/NS.1821.001.IDT_i7_33---IDT_i


`

**Comment by jorondo1** [comment]
ouin on dirait qu'il y a un character ˆ pour le saut de ligne...

j'ai tout manipulé dans excel d'abord, puis sauvegardé en txt (somehow je peux pas save en tsv direct), puis changer l'extension avant de l'envoyer sur ip29 avec `sftp> put `
[CUSTOM_DB_SAMPLE.txt](https://github.com/jflucier/ILL_pipelines/files/8522145/CUSTOM_DB_SAMPLE.txt)

je te joins le fichier que j'ai créé

**Comment by jflucier** [comment]
vien de tester et ca fonctionne pas le dos2unix...

Solution:
sed 's/^M/\
/g' filename

ou ^M = ctrl v + ctrl M

**Comment by jflucier** [comment]
je lai fait sur ton fichier

**Comment by jflucier** [comment]
Ceic dit, pour ta question initial... si c juste pour tester le pipeline, t'as pas besoin de rouler 186 echantillon car tu vas bouffer l'allocation pour rien. Vas sy plus raisonnablement et minimallement. Une 10aine suffirait non?

**Comment by jorondo1** [comment]
super thanks 
oui je vais faire ça
