### ISSUE TITLE
rendre les noms de variables plus intuitifs?

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#12]
Est-ce qu'on pourrait rendre les noms de variable plus intuitifs pour les deux tsv? C'est un détail technique mais moi même j'avais de la misère à m'y retrouver un peu.

TSV avec les raw fastq (3 colonnes) pourrait simplement s'appeler 
RAW_SAMPLES_LIST_TSV

Celui avec les cat-paired files
PREPROC_SAMPLES_LIST_TSV

**Comment by jflucier** [comment]
juste pour etre certain c'est bien:

CUSTOM_DB_SAMPLE_TSV --> RAW_SAMPLES_LIST_TSV

et

HUMANN_RUN_SAMPLE_TSV --> PREPROC_SAMPLES_LIST_TSV

??

**Comment by jorondo1** [comment]
oui ! merci
sorry je vais répondre un peu moins vite cet été, je fais seulement une douzaine d'heures semaine au lab

**Comment by jflucier** [comment]
done

commit [here](https://github.com/jflucier/ILL_pipelines/commit/f9d0d365de1353897e668aa4d959617614f5829f)
