### ISSUE TITLE
ajout subdir pour slurm log

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#13]
vu qu'il y a un log par sample je créerais un subdir par job pour chaque code

un exemple pour le scrpt 03 [ici](https://github.com/jflucier/ILL_pipelines/blob/09fd1c0e47ade6f85eb119c5987da8911bf202b0/humann_custom/03_humann_custom_run.sh#L24) je remplacerais par :
`#SBATCH -o '${OUPUT_PATH}'/slurm_logs/custom_humann-%A_%a.slurm.out`

faudrait aussi ajouter mkdir '${OUPUT_PATH}'/slurm_logs au bon endroit j'imagine

**Comment by jflucier** [comment]
done

commit [here](https://github.com/jflucier/ILL_pipelines/commit/886be7ab3954bb8ef7c58db977bd17eb713d3078)
