### ISSUE TITLE
database update

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#17]
metaphlan4 est sorti y'a 2 semaines et avec ça une mise à jour importante de la db chocophlan qu'on utilise

je ne suis pas certain de la meilleure approche pour faire la mise à jour étant donné qu'on n'utilise pas metaphlan, j'ai posté ici pour avoir leurs conseils sur la meilleure façon d'intégrer la nouvelle db à notre pipeline https://forum.biobakery.org/t/updating-the-new-chocophlan-db/3746

mais just so you know on aimerait que la db soit à jour pour quand on va commencer le profilage provid. J'aimerais comprendre le processus pour éventuellement être autonome dans la màj, qui risque d'arriver à tous les 2 ans (ou même moins) étant donné que les db de référence grossissent de plus en plus vite

**Comment by jflucier** [comment]
je crosi avoir trouver le download a cet adresse:

[](http://huttenhower.sph.harvard.edu/humann_data/chocophlan/)

je suis en train de download dans /nfs3_ib/ip29-ib/ssdpool/shared/ilafores_group/humann_dbs/

**Comment by jflucier** [comment]
je soupconne que c exactement la meme bd que celle tagge au 15-Apr-2022

**Comment by jorondo1** [comment]
pas sûr que ce soit la bonne, on cherche une db de janvier 2021 en fait mpa_vJan21_CHOCOPhlAnSGB_NEW selon https://github.com/biobakery/MetaPhlAn/wiki/MetaPhlAn-4

**Comment by jflucier** [comment]
en passant le v4 de metaphlan est tagge comme beta... toucherais pas a ca.

semble en avoir une par anne et celle que je pointe est la derniere

**Comment by jorondo1** [comment]
ok parfait
metaphlan4 a été présenté au congrès auquel j'ai assisté la semaine passée, je vais garder un oeil dessus sûrement que le release officiel va suivre bientôt je te tiens au courant

**Comment by jflucier** [comment]
la bd chocophlan.v201901_v31 est maitnenant installe cet endroit:

/ssdpool/shared/ilafores_group/humann_dbs/chocophlan.v201901_v31
