### ISSUE TITLE
màj des shells

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#19]

**Comment by jorondo1** [comment]
il faudrait mettre à jour les noms de fichiers dans le readme du git[ ici](il faudrait mettre à jour les noms de fichiers dans le readme du git
)

**Comment by jflucier** [comment]
ouin pas trop touche a la doc.... ca change c temps ci. Je vais refaire la doc une fois termine.

perd pas tropd et emps avec ca pour tout de suite

**Comment by jorondo1** [comment]
ok tiens-moi au courant quand ce sera le temps, je ferai le tour en détail

**Comment by jflucier** [comment]
la doc est updater.
