### ISSUE TITLE
Kraken databases discussions

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#2]
J'ai continué à réfléchir sur le problème de la grosse db kraken. Je pense qu'on devrait essayer de le résoudre avec « big data » en tête. 

Les databases de référence sont vouées à grossir de plus en plus vite (et notre pipeline va y contribuer!); pour des approches métagénomiques _reference-based_, comme Kraken et Humann, on va vouloir le plus possible utiliser des db à jour et complètes, et même parfois provide/build nous-même des db curated pour répondre à des questions plus spécifiques.

Bref, peut-être que le module Kraken pourrait/devrait être envoyé dans un module à part avec des ressources différentes. De toute façon, kraken va servir à autre chose qu'un input bugs-list (ex. dans metaWRAP), donc ce sera bien de l'avoir en module indépendant.

Je lance la discussion. Pour l'instant laissons ça comme c'est et on y reviendra lorsque ce sera nécéssaire!

**Comment by jflucier** [comment]
oui mais les outils devront suivre... jai vu des truc developpe en AI qui competionne kraken. Ca demanderais d'etre teste. 

Je crois que si on y va aavec la grosse bd, on a juste a fabrique le buglist sur narval qui a bcp bcp plus de compute power que mp2.

Lorsque le pipleine sera fonctionnel, je propose que nous testons la gen de buglist complet sur narval. D'apres moi ca va bien fonctionner.
