### ISSUE TITLE
new preproc script

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#20]
salut j'essaie de run le preprocessing script mais le shell généré par bash $HUMANN_CUSTOM_INSTALL/generateslurm_preprocess.kneaddata.sh my.example.config

s'arrête à [cette ligne](bash $HUMANN_CUSTOM_INSTALL/generateslurm_preprocess.kneaddata.sh my.example.config)

voir mon test /ip29/ilafores_group/projet_PROVID19/preprocess/preprocess.kneaddata.slurm.sh

j'pense qu'il manque un echo ou un guillemet à qqpart mais je suis pas sûr où ?

**Comment by jflucier** [comment]
ton lien fonctionne pas

je check

**Comment by jflucier** [comment]
essaie ca:

```
newgrp def-ilafores
cd /project/def-ilafores/analysis/20220615_moss_7samples_test
cp /project/def-ilafores/common/ILL_pipelines/my.example.config 20220615_moss_7samples_test.config

# 7 espèces hôtes:
# /ip29/ilafores_group/sarahi/subsample_ass_test.tsv
cp /ip29/ilafores_group/sarahi/subsample_ass_test.tsv .

## edit config file
vi 20220615_moss_7samples_test.config

sh /project/def-ilafores/common/ILL_pipelines/generateslurm_preprocess.kneaddata.sh $PWD/20220615_moss_7samples_test.config
#sbatch --array=1-7 /project/def-ilafores/analysis/20220615_moss_7samples_test/preprocess/preprocess.kneaddata.slurm.sh

```

**Comment by jorondo1** [comment]
je suis pas sûr de comprendre ce que tu me proposes ?
scuse je suis pas dans les moss je suis rendu avec les données provid

voici ce que j'ai fait :

1. copié/edit le config file qui se trouve maintenant ici : /ip29/ilafores_group/projet_PROVID19
(mon fichier raw.sample.test.tsv qui se trouve dans ce dir)

2. bash $HUMANN_CUSTOM_INSTALL/generateslurm_preprocess.kneaddata.sh my.example.config

et le fichier sortant, /ip29/ilafores_group/projet_PROVID19/preprocess/preprocess.kneaddata.slurm.sh

est incomplet, s'arrête à [cette ligne](https://github.com/jflucier/ILL_pipelines/blob/cba9b8e8db2193d4cd5e17ce512d23279615f64a/generateslurm_preprocess.kneaddata.sh#L47)

**Comment by jorondo1** [comment]
ok je pense que c'est pas incomplet, c'est juste que le principe semble avoir changé depuis la dernière fois, le shell call un autre shell: /project/def-ilafores/common/ILL_pipelines/scripts/preprocess.kneaddata.sh

bref, si je sbatch --array=1-29 /ip29/ilafores_group/projet_PROVID19/preprocess/preprocess.kneaddata.slurm.sh , après quelques secondes il n'y a plus rien dans squeue et je n'ai pas de log pour voir ce qui s'est passé, peux-tu m'aider à comprendre ?

**Comment by jflucier** [comment]
c quoi ton repertoire de travail?

as-tu le anchor nfs a tes path /nfs3_ib/... 

bref donne ton working path et ton sername et je vais checker ca

**Comment by jorondo1** [comment]
oui en fait je n'ai qu'adapté le fichier my.example.config copié aujourd'hui

est-ce que je dois aussi mettre /nfs3_ib/ à mon output path? parce que le fichier config ne l'a pas dans les valeurs par défaut

bref je travaille avec le fichier /ip29/ilafores_group/projet_PROVID19/my.example.config mon username est ronj2303

**Comment by jorondo1** [comment]
salut JF j'ai besoin de ton aide, je n'arrive pas à faire rouler le code de preprocessing, j'aimerais passer nos samples dans le pipeline complet de profiling le plus rapidement possible pour qu'on puisse regarder notre data un peu.

J'ai vérifié les anchor dans /ip29/ilafores_group/projet_PROVID19/my.example.config je pense que tout est ok

export HUMANN_CUSTOM_INSTALL=/project/def-ilafores/common/ILL_pipelines

bash $HUMANN_CUSTOM_INSTALL/generateslurm_preprocess.kneaddata.sh my.example.config

sbatch --array=1-29 /ip29/ilafores_group/projet_PROVID19/preprocess/preprocess.kneaddata.slurm.sh

quand je submit ça reste en queue 2-3 secondes et ça disparaît, aucun log n'est produit donc je ne sais pas comment déboguer ça

**Comment by jflucier** [comment]
Bonjour

c'est parti sous ton username

squeue -u ronj2303

Presentement l'etape kneaddata. Tu as acces au log slurm a cet endroit:
/nfs3_ib/ip29-ib/ip29/ilafores_group/projet_PROVID19/preprocess/preprocess.kneaddata-18601_10.slurm.out

Si tu regarde un des log slurm tu verras une ligne ressemblant a ceci:
```
copying fastq /nfs3_ib/ip29-ib/ip29/ilafores_group/projet_PROVID19/data/NS.1891.002.IDT_i7_3---IDT_i5_3.GQ8_R1.fastq.gz
copying fastq /nfs3_ib/ip29-ib/ip29/ilafores_group/projet_PROVID19/data/NS.1891.002.IDT_i7_3---IDT_i5_3.GQ8_R2.fastq.gz
running kneaddata. kneaddata ouptut: /localscratch/ronj2303.18611.0/preprocess/GQ8/

```
Pour consulter le log d'execution de kneaddata, tu dois ouvrir /nfs3_ib/ip29-ib/ip29/ilafores_group/projet_PROVID19/preprocess/preprocess.kneaddata-GQ8.log

Les erreurs lorsque tu essayais de lancer l'analyse etaient tous du a des nfs anchor (/nfs3_ib/ip29-ib) manquants:

- manquait anchor au filepath des fastq specifier dans raw.sample.test.tsv. J'ai modifier ton fichier en effectuant les commandes suivantes:
```
cd /nfs3_ib/ip29-ib/ip29/ilafores_group/projet_PROVID19/
cp raw.sample.test.tsv raw.sample.test.tsv.bak
sed -i 's/\/ip29/\/nfs3_ib\/ip29-ib\/ip29/g' raw.sample.test.tsv

```
- dans le fichier my.example.config, la variable output_path n'avait pas le anchor nfs egalement. 

- pour generer les scripts, il faut faire un cd avec anchor nfs comme ceci:
```
cd /nfs3_ib/ip29-ib/ip29/ilafores_group/projet_PROVID19/
sh /project/def-ilafores/common/ILL_pipelines/generateslurm_preprocess.kneaddata.sh $PWD/my.example.config
sbatch --array=1-29 /nfs3_ib/ip29-ib/ip29/ilafores_group/projet_PROVID19/preprocess/preprocess.kneaddata.slurm.sh

```
