### ISSUE TITLE
kick off kraken

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#21]
j'essaie de partir kraken avec la commande suivante

```
cd /nfs3_ib/ip29-ib/ip29/ilafores_group/projet_PROVID19/

sh /project/def-ilafores/common/ILL_pipelines/generateslurm_taxonomic_profile.sample.sh $PWD/my.example.config

```
mais j'ai une erreur comme quoi la db kraken n'est pas accessible : 

```
##**** KRAKEN2 database index not found. ****
## Please verify. An index file with the following name should be found: /nfs3_ib/ip29-ib/ssdpool/shared/ilafores_group/kraken2_dbs/k2_pluspfp_16gb_20210517/hash.k2d

```

 QUand j'essaie de vérifier le path 
/nfs3_ib/ip29-ib/ssdpool/shared/ilafores_group/kraken2_dbs/k2_pluspfp_16gb_20210517/ 

j'ai access denied (mais j'ai accès au dir parent)

**Comment by jorondo1** [comment]
fyi j'ai réussi à le partir avec la grosse db, donc y'aurait juste les permissions de la 16gb à changer je crois

**Comment by jflucier** [comment]
done
