### ISSUE TITLE
typo 

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#22]
dans 
/project/def-ilafores/common/ILL_pipelines/scripts/taxonomic_profile.allsamples.sh

la ligne 25, devrait être 
${EXE_PATH}/taxonomic_profile.allsamples.checkenv.sh
avec un S à allsamples

**Comment by jorondo1** [comment]
en fait on dirait que la version n'est pas à jour, si je compare à https://github.com/jflucier/ILL_pipelines/blob/main/generateslurm_taxonomic_profile.allsamples.sh

**Comment by jflucier** [comment]
done
