### ISSUE TITLE
all samples bugs list

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#23]
pour rouler taxonomic_profile.allsamples.sh, je ne trouve pas où on peut set le cutoff de quelle proportion des bugs on prend ?

aussi, est-ce que ce code ne devrait pas rouler sur une x-fat node?

**Comment by jflucier** [comment]
le script roule combine_kreports.py avec un path avec wildcard permettant d'aller chercher les kraken reports d'echantillon individuel a considerer

par defaut, ca prend les rapport a partir de cet endroit:
export TAXONOMIC_ALL_BRACKEN_KREPORTS="$OUPUT_PATH/taxonomic_profile/*/*_bracken/*_bracken_S.kreport"

pour les x fat node  p-e.... a tester d'abord avec 30G.

quel commande du script permet de specifier le cutoff de proportion de bugs?

**Comment by jorondo1** [comment]
Il s'agit du script qui va créer la bugslist et ensuite créer une custom_db de chocophlan. 

Si on utilise le bugs list complet, dans ce cas-ci la custom_db contiendra ~6000 génomes, donc aussi ben aller sur les grosses nodes car on se souvient que ça prenait un temps de fou.

Dans les débuts du code j'avais une commande qui enlevait les espèces avec moins de x reads 
`egrep -w -v '1|2|3|4|5|6|7|8|9|10' ` par exemple, mais ça n'a pas beaucoup d'impact (on passe de 6000 à 5500 environ ici)

La discussion qu'on n'avait pas conclue est à savoir si c'est pas plus efficace de rouler humann sur la database complète (qui inclut quelque chose comme 12 000 génomes) considérant le temps que ça prend de build/index un gros subset.

On pourrait s'appeler pour en jaser de vive voix?
