### ISSUE TITLE
fully translated humann run

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#24]
on aurait besoin de pouvoir produire une run de humann utilisant seulement la db translated

J'avais déjà monté le script pour ça dans le passé [voir ici](https://github.com/jflucier/ILL_pipelines/issues/15#issuecomment-1129013564). 

C'est peut-être pas la meilleure approche; un script d'abord pour le NT search, puis un autre pour le Prot search où les paramètres dépendaient de s'il y avait ou non un output du NT search déjà présent). J'avais fait ça parce qu'on veut run le NT search sur des nodes large, mais le PROT search ne gagne pas à être sur ces nodes. Ça permet surtout de rouler uniquement le PROT search, ce qu'on va vouloir faire éventuellement pour comparer les approches.

Pour l'instant vu que je serai surtout intéressé à comparer une full-NT search à une full-PROT search, on pourrait s'en tenir à une switch dans le config file qui modifie la commande humann de la façon suivante, après quoi j'ajusterai les paramètres slurm :

**DUAL_MODE**: commande actuelle, soit NT search suivi de PROT search sur les non-alignés

**NT_MODE**: 
1. enlever --protein-database
2. ajouter --bypass-translated-search
 
**PROT_MODE**:
1. enlever --nucleotide-database --bypass-nucleotide-index
3. ajouter --bypass-nucleotide-search

Il faudrait que cette switch change également le nom du output directory pour éviter les conflits ou données écraser quand on comparera plusieurs modes sur le même dataset.

**Comment by jflucier** [comment]
done

reste a tester cette patch.

https://github.com/jflucier/ILL_pipelines/commit/aecbd752a510a302982eb29a0e2bbeac490864bb
