### ISSUE TITLE
bugs-list in db name

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#27]
cette erreur est toujours présente dans le config :
https://github.com/jflucier/ILL_pipelines/issues/25#issuecomment-1176560294

**Comment by jflucier** [comment]
je vois pas l'erreur que tu mentionne dans les log de functionnal_profile

peux-tu me pointer vedrs un de ces log stp

**Comment by jorondo1** [comment]
c'est pas dans un log, c'est juste une ligne du default config qu'il faut changer pour enlever le suffixe -bugs_list

**Comment by jflucier** [comment]
done

https://github.com/jflucier/ILL_pipelines/commit/ede28fa80f67c093a758a795f8f42f2a39aa69d7
