### ISSUE TITLE
slurm base vs fat nodes

### ISSUE THREAD

**Issue by jflucier** [jflucier/ILL_pipelines#28]
@jorondo1 [jorondo1](https://github.com/jorondo1)

c'est bien pour le functionnal profiling que tu as besoin de 2 type de configuration slurm en terme de memoire?

Voici ce que je pense:
Dual: fat node configuration (125G, 24 cpu)
NT: fat node configuration (125G, 24 cpu)
PROT: base node (30G, 24 cpu)

C'etait p-e pour le taxonomic profile que tavais besoin de ca... me rappel plus.

Merci

**Comment by jorondo1** [comment]
oui exact !

**Comment by jflucier** [comment]
done

https://github.com/jflucier/ILL_pipelines/commit/c9a8e95ccb110f84adb935817a6160feada7f16f
