### ISSUE TITLE
skip normalization

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#3]
Future modification (not a priority) :

Remove humann_renorm step; keep raw counts for downstream analysis to account for the compositional nature of data. All subsequent humann steps can be performed on raw counts.

**Comment by jflucier** [comment]
do you mean this [line](https://github.com/jflucier/ILL_pipelines/blob/6d36038463b4b22cc0160808beb3973c688df789/humann_custom/03_humann_custom_run.sh#L95)

**Comment by jflucier** [comment]
must be it since only place humann_renorm is called.

Please confirmand i will delete & release.

**Comment by jorondo1** [comment]
exactly, so the loop right above it ($norm_method == "cpm") becomes irrelevant and the subsequent files will not have the $norm_method suffix

while you're at it, the operation at [this line](https://github.com/biobakery/humann#humann_split_stratified_table) can actually be done using a humann utility, namely [this one](https://github.com/biobakery/humann#humann_split_stratified_table). It takes the .tsv created by the humann_regroup script loop and splits them exactly like I want (stratified levels + community level, called "unstratified" here)

**Comment by jflucier** [comment]
commented this step. See [here](https://github.com/jflucier/ILL_pipelines/blob/b6fd8610df2d368027dec2607a0eb25309a5883d/humann_custom/03_humann_custom_run.sh#L95)

released on ip29

**Comment by jflucier** [comment]
damm just saw we need to remove norm for loop, will proceed with this modif

**Comment by jorondo1** [comment]
yes j'allais justement t'écrire pour dire que faut enlever la loop
ça a l'air good
