### ISSUE TITLE
petits changements au script preprocess

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#31]
Salut!
J'ai réglé quelques problèmes dans le preprocessing. Pourrais-tu:

enlever [cette ligne](https://github.com/jflucier/ILL_pipelines/blob/61a89d2070fca68025b27769a91fe085da957d05/scripts/preprocess.kneaddata.sh#L56)
modifier [cette option par défaut](https://github.com/jflucier/ILL_pipelines/blob/61a89d2070fca68025b27769a91fe085da957d05/my.example.config#L22) pour ceci:
`export PREPROCESS_KNEADDATA_TRIMMOMATIC="ILLUMINACLIP:/cvmfs/soft.mugqic/CentOS6/software/trimmomatic/Trimmomatic-0.39/adapters/TruSeq3-PE-2.fa:2:30:10 SLIDINGWINDOW:4:30 MINLEN:100"
`
et l'option par défaut de bowtie pour `--very-sensitive-local`

sorry j'ai pas encore commencé à essayer le git clone, ça aurait été une belle occasion..!

merci !

**Comment by jflucier** [comment]
done

https://github.com/jflucier/ILL_pipelines/commit/0e8b7cb6deba5c5927c2f64319ae6497020a8915
