### ISSUE TITLE
first commit

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#32]
let me know if I did right...?!

**Comment by jflucier** [comment]
looks good!

va merger ca plus tard et closer ce ticket ensuite

**Comment by jorondo1** [comment]
cool merci
je l'ai pas testé parce q ue c'est assez basic, mais est-ce ok  si aucun argument n'est donné?

**Comment by jflucier** [comment]
done

https://github.com/jflucier/ILL_pipelines/commit/e9d8e358ccb94714f4d7c4f93cbfd231b551ed79

**Comment by jflucier** [comment]
added validaiton

https://github.com/jflucier/ILL_pipelines/commit/b0681f11ec203a0a77b5253850c8f2a0a2fcd7b4

**Comment by jflucier** [comment]
joubliais... 

jai delete la branche iss-slurm_email

tu dois te recreer un branche a partir de main avant de refaire des changements / fix

```
git branch new_branch_name
git checkout new_branch_name

```

**Comment by jorondo1** [comment]
yes c'est bien ce que j'ai fait, en gros:

```
git checkout -b iss-slurm_email # branche mon code

# changer mes affaires

git add .
git commit -m 'message'
git push origin iss-slurm_email
```

**Comment by jflucier** [comment]
oui mais la tu dois faire

```
git checkout main
git pull origin main
git branch new_branch_name
git checkout new_branch_name
```
