### ISSUE TITLE
sourmash

### ISSUE THREAD

**Issue by jflucier** [jflucier/ILL_pipelines#34]
Salut JF,

Est-ce que tu pourrais nous installer [sourmash](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsourmash.readthedocs.io%2Fen%2Flatest%2Findex.html&data=05%7C01%7CJean-Francois.Lucier%40USherbrooke.ca%7C6c8e8c4c64944338c21708da6feb0f8c%7C3a5a8744593545f99423b32c3a5de082%7C0%7C0%7C637945352603215259%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ae3tOkYpihBIyt928tiqLau2vt2xV1D5hRJCF2FBVUU%3D&reserved=0), j'aimerais faire des vérifications et un peu d'exploration avec cette approche.

J'aurais besoin des db suivantes : 
[GTDB R07-RS207 all genomes (318k)](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsourmash.readthedocs.io%2Fen%2Flatest%2Fdatabases.html%23gtdb-r07-rs207-all-genomes-318k&data=05%7C01%7CJean-Francois.Lucier%40USherbrooke.ca%7C6c8e8c4c64944338c21708da6feb0f8c%7C3a5a8744593545f99423b32c3a5de082%7C0%7C0%7C637945352603215259%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wJmQL2dWKem6wfd3WTiJPzMH9xjNRBpf7V%2FZv2bA9nc%3D&reserved=0)
[genbank-2022.03-viral-k21.zip](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsourmash.readthedocs.io%2Fen%2Flatest%2Fdatabases.html%23genbank-viral&data=05%7C01%7CJean-Francois.Lucier%40USherbrooke.ca%7C6c8e8c4c64944338c21708da6feb0f8c%7C3a5a8744593545f99423b32c3a5de082%7C0%7C0%7C637945352603215259%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pzbVnd2%2BVIrVIyvCtIGSeoP%2Fh9cC%2BBOEebv0rIuTWkI%3D&reserved=0)
[genbank-2022.03-fungi-k21.zip](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsourmash.readthedocs.io%2Fen%2Flatest%2Fdatabases.html%23genbank-fungi&data=05%7C01%7CJean-Francois.Lucier%40USherbrooke.ca%7C6c8e8c4c64944338c21708da6feb0f8c%7C3a5a8744593545f99423b32c3a5de082%7C0%7C0%7C637945352603215259%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DqEDY7%2B74nOWBASHtbZizWfnoZqexk85JIlYDZx1RKU%3D&reserved=0)
Pourrais-tu m'écrire une commande pour partir ce programme et Bowtie2 ensemble?

thanks !

**Comment by jflucier** [comment]
la bd de fungi fait 40G et le downlooad a plante 3 fois a date et pas capable de me rendre a 1G....

@jorondo1 Es-tu en mesure de telecharge et de mettre le fichier a cet endroit /nfs3_ib/ip29-ib/ssdpool/shared/ilafores_group/sourmash_db ?

**Comment by jflucier** [comment]
jai installe et teste partiellement avec ce [tuto](https://sourmash.readthedocs.io/en/latest/tutorial-lemonade.html), tu peux l'utilise de cette facon:

`conda activate sourmash`

Les resultat du tuto se trouve a cet endroit:
/ssdpool/shared/ilafores_group/sourmash_db/test

**Comment by jflucier** [comment]
@jorondo1 
oups joubnliais un point, je comoprend pas trop la partie bowtie de ton email?

**Comment by jorondo1** [comment]
Hey! Merci pour l'installation, désolé pour le délai, je partais en vacances comme tu revenais. Je commence mon 2e stage aujourd'hui, donc full time jusqu'à Noël.

> @jorondo1 oups joubnliais un point, je comprend pas trop la partie bowtie de ton email?

Je demandais parce que quand je te faisais installer un programme tu me sortais toujours une grosse ligne avec tous les programmes à partir, du genre 

```
export MUGQIC_INSTALL_HOME=/cvmfs/soft.mugqic/CentOS6
module use $MUGQIC_INSTALL_HOME/modulefiles
module load StdEnv/2020 gcc/9 python/3.7.9 java/14.0.2 mugqic/bowtie2/2.3.5 \
	mugqic/trimmomatic/0.39 mugqic/TRF/4.09 mugqic/fastqc/0.11.5 mugqic/samtools/1.14

```
Est-ce que je n'aurais pas besoin de ça si je veux run sourmash sur les nodes? 

Aussi, 
> @jorondo1 Es-tu en mesure de telecharge et de mettre le fichier a cet endroit /nfs3_ib/ip29-ib/ssdpool/shared/ilafores_group/sourmash_db ?

est-ce que c'est réglé ou veux-tu que j'essaie?

**Comment by jflucier** [comment]
je viens de reessayer et impossible de telecharge leur bd de fungi:

```
|11:53:45|jflucier@ip29:[sourmash_db]> curl -JLO https://dweb.link/ipfs/bafybeibrirvek4lxn6hh3wgsmtsd5vz5gtmewpzeg364bix3hojghwmygq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  7 2528M    7  192M    0     0  2672k      0  0:16:08  0:01:13  0:14:55     0
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)

```

Une fois que tu fais `conda activate sourmash` tu devrais avoir acces atous sur les nodes. Si bowtie na pas ete installe dans l'env, fait le module load de bowtie une fois ton env conda active.

**Comment by jorondo1** [comment]
Concernant la bd fungi, veux-tu que j'ouvre un issue sur leur git ou as-tu une piste de solution ?

**Comment by jflucier** [comment]
go et reecrie ici le lien vers issue pour suivi

**Comment by jflucier** [comment]
je viens de repartir le download

ca lair de mieux fonctionner maintenant

je te dit lorsque termine

**Comment by jflucier** [comment]
c fait.

les db sont dans /ssdpool/shared/ilafores_group/sourmash_db

enjoy!
