### ISSUE TITLE
run metawrap par modules

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#36]
s'assurer qu'on puisse re-rouler le bin_refinement sans avoir à refaire le process d'assemblage au complet

aussi, est-ce que les modules d'annotations seront dans un script indépendant? Roary, prokka, gtdb-tk

**Comment by jflucier** [comment]
> aussi, est-ce que les modules d'annotations seront dans un script indépendant? Roary, prokka, gtdb-tk

je vais faire un module qui les roules tous ensemble. Je peux facilement ensuite faire de smodule separer si on juge pertinent. C pas assez long pour separer selon moi

**Comment by jflucier** [comment]
Note: code change done (https://github.com/jflucier/ILL_pipelines/commit/351939d151bc5c5adfa066efeeff1cfb20bfda30)

Still need to release, cannot because moss jobs still waiting to execute
