### ISSUE TITLE
contigs functional annotation with kofamscan

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#37]
J'aimerais pouvoir monter un script où j'utiliserais [Prodigal 2.6.3](https://github.com/hyattpd/Prodigal), [Kofamscan 1.3.0](https://github.com/takaram/kofam_scan) et [KEGG-decoder 1.2.2](https://github.com/bjtully/BioData/blob/master/KEGGDecoder/README.md). Je m'inspire de [ce tuto](https://github.com/mblstamps/stamps2022/blob/main/functional_annotation/functional_annotation.md#ortholog-annotation-with-kofamscan) que j'ai essayé pendant mon cours. Si t'as besoin de voir mon script je te l'enverrai mais il n'est pas tout à fait fini.

**Comment by jflucier** [comment]
Mon opinion,

on devrait utilise prokka au lieu de prodigal pour predire le proteome. Ensuite, on passe le fasta de proteine predit a roary et kofamscan+keggdecoder

Ca sert a rien de rouler prodigal et prokka en parralele... tu obtiendras pas vraiment plus d'info. Ca complexifie les post-analyse pour rien.

**Comment by jorondo1** [comment]
En fait la première étape de prodigal est de rouler prokka pour créer des fasta de protéines prédites, après quoi ces fichiers sont cherchés contre différentes db

pourrais-tu me montrer comment partir prokka indépendamment de notre pipeline, je veux rouler kofamscan sur des contigs déjà assemblés, c'est le projet d'une autre collègue

**Comment by jflucier** [comment]
non pas encore installer ca.

va essayer de faire ca aujourd'hui.

**Comment by jflucier** [comment]
pas ete facile ce dernier install. 

Pour utilise keggdecoder:

```
conda activate keggdecoder
KEGG-decoder -h

```

**Comment by jorondo1** [comment]
merci beaucoup 
est-ce que je peux activer ces trois modules dans le même script, dans un seul header? Si non, quel est le meilleur moyen de travailler avec prokka + kofamscan + keggdecoder dans un même script ?

**Comment by jflucier** [comment]
Pour te simplifier la vie, jai tout installe sous un meme environnement.

```
module load StdEnv/2020
conda activate keggdecoder
prokka -h
/project/def-ilafores/common/kofam_scan/exec_annotation -h
KEGG-decoder -h

```

**Comment by jorondo1** [comment]
le config.yml de kofamscan est vide, je peux define --cpu, -k et -p dans ma commande mais je pense que je dois pointer vers hmmsearch et parallel, où sont-ils ?

**Comment by jorondo1** [comment]
Je ne sais pas si c'est le bon endroit, mais j'essaie de pointer vers /project/def-ilafores/common/kofam_scan/lib/kofam_scan/parallel.rb et j'obtiens l'erreur suivante:

/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64/ruby/2.4.0/open3.rb:199:in `spawn': Permission denied - /project/def-ilafores/common/kofam_scan/lib/kofam_scan/parallel.rb (Errno::EACCES)

**Comment by jorondo1** [comment]
Je crois les avoir trouvés, dans /project/def-ilafores/miniconda3/envs/keggdecoder/bin/

J'essaie de rouler exec_annotation sans succès, la commande stall et quand je regarde Top y'a aucune utilisation de CPU à travers le temps. L'avais-tu testée? Voici mon code:

```
export exec_annotation=/project/def-ilafores/common/kofam_scan/exec_annotation
export _in_dir=/nfs3_ib/ip29-ib/ip29/ilafores_group/rosaelle/syncom
export _bn=Leaf351
export _infile=$_in_dir/PRJNA297956_assembly2015/*${bn}*.fna
export _out_KO=${in_dir}/kofamscan_out

$exec_annotation $_infile --config config_test.yaml \
-f mapper \
-o $_out_KO/${bn}.txt
```
mon config file est ici ip29/ilafores_group/rosaelle/syncom/config_test.yaml

![Bildschirmfoto 2022-09-16 um 11 19 57](https://user-images.githubusercontent.com/97983060/190673765-4ca33180-cce1-473d-a6de-f259a8c361ea.png)

**Comment by jorondo1** [comment]
je me suis débogué, exec_annotation émet zero verbose mais j'ai réalisé que je pointais vers le mauvais infile, Désolé pour tout ça ! 🙃

**Comment by jflucier** [comment]
PTI, check aussi le screenshot, hmmsearch tourne a plusieurs threads mais a 0%,.... c pas trop ce que ce logiciel fait.
