### ISSUE TITLE
Roary integration

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#38]
Est-ce que l'output de Roary permet de comparer les samples entre eux en distinguant chaque MAG qui s'y trouve? Ou est-ce qu'il compare seulement les MAGs d'un sample entre eux ?

**Comment by jflucier** [comment]
roary travail sur les annotation de gene

donc il compare les proteomes predit entre eux et cluster les proteine identique entre les sample sensemble.

Je me sert de cet outil de routine pour plusieurs de mes projets lorsque je dois comparer les proteomes entre differentes souches  bacteriennes
