### ISSUE TITLE
cannot stat sourmash db

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#40]
Sur les noeuds quand j'essaie de copier la db j'ai l'erreur: `cp: cannot stat '/ssdpool/shared/ilafores_group/sourmash_db/gtdb-rs207.genomic.k21.zip': No such file or directory` alors que le chemin est le bon. As-tu une idée ce qui peut causer ça? 

Si je roule _sourmash gather_ sans copier la db (en pointant sur le ssd pour la db) la commande reporte une erreur. C'est pour essayer de régler ça que j'ai pensé copier la db dans mon tmpdir.

Mon script : /nfs3_ib/ip29-ib/ip29/ilafores_group/projet_PROVID19/scripts/sourmash_test2.sh

Log avec l'erreur de cp: /nfs3_ib/ip29-ib/ip29/ilafores_group/projet_PROVID19/taxonomy_sourmash/slurm_logs/sourmash_-70851_43.out

Log avec l'erreur si je pointe sourmash gather vers le ssd: /nfs3_ib/ip29-ib/ip29/ilafores_group/projet_PROVID19/taxonomy_sourmash/slurm_logs/sourmash_-70850_43.out

**Comment by jflucier** [comment]
tu dois ajouter le anchor nfs pour le cp:

`export __DB_DIR=/nfs3_ib/ip29-ib/ssdpool/shared/ilafores_group/sourmash_db`

**Comment by jorondo1** [comment]
ah sti... merci
