### ISSUE TITLE
changement de config file

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#45]
Salut, j'essaie de lancer kraken en utilisant mon ancien config file et ça ne fonctionne pas avec les nouveaux scripts. J'imagine que les variables ont changé alors j'essaie d'aller chercher le nouveau config file, j'en ai trouvé un ici /project/def-ilafores/common/ILL_pipelines/metawrap_custom/my.example.config mais il est presque vide, je ne vois pas les paramètres kraken. 

Est-ce que je peux rouler le module taxonomy kraken indpéendamment ou c'est tout rendu automatisé?

**Comment by jflucier** [comment]
non pu besoin de config file.

jai documente tout ca dans la page d'acceuil du projet:
https://github.com/jflucier/ILL_pipelines#Run-Kraken2-taxonomic-profile
