### ISSUE TITLE
assembly échantillon GQ35 (array=4)

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#46]
Il me manque un échantillon qui n'a pas assemblé, je viens d'essayer et j'ai le message suivant:
```
FATAL:   could not open image /nfs3_ib/ip29-ib/ip29/ilafores_group/projet_PROVID19/ILL_pipelines/containers/metawrap.1.3.sif: failed to retrieve path for /nfs3_ib/ip29-ib/ip29/ilafores_group/projet_PROVID19/ILL_pipelines/containers/metawrap.1.3.sif: lstat /nfs3_ib/ip29-ib/ip29/ilafores_group/projet_PROVID19/ILL_pipelines/containers/metawrap.1.3.sif: no such file or directory
```

J'ai lancé avec la commande suivante 
`sbatch --array=4 /nfs3_ib/ip29-ib/ip29/ilafores_group/projet_PROVID19/denovo_assembly/assembly_bin_refinement.metawrap.slurm.sh`

une idée qu'est-ce qui se passe?

**Comment by jflucier** [comment]
hmmm.... ya de quoi de bizarre. As-tu generer le script slurm de cette facon?

export ILL_PIPELINES=/project/def-ilafores/analysis/test/ILL_pipelines

bash $ILL_PIPELINES/generateslurm_assembly_bin_refinement.metawrap.sh \
--sample_tsv $PWD/preprocess/taxonomic_profile.sample.tsv \
--out /project/def-ilafores/analysis/test/ \
--slurm_email "email@domain.ca" \
--assembly --binning --refinement

**Comment by jorondo1** [comment]
J'ai réessayé avec exactement la commande que tu me donnes, j'ai la même erreur... voici le log /nfs3_ib/ip29-ib/ip29/ilafores_group/projet_PROVID19/denovo_assembly/logs/assembly_bin_refinement-84961_4.slurm.out

je travaille à partir d'une copie du repo /nfs3_ib/ip29-ib/ip29/ilafores_group/projet_PROVID19/ILL_pipelines/

**Comment by jflucier** [comment]
l'image metawrap.1.3.sif n'est pas sur git hub car c'est trop lourd (5.5G) et doit etre regen a partir la recette dans /project/def-ilafores/common/ILL_pipelines/containers/metawrap.1.3.def

Cette etape prend bcp de temps. Question, pk tu travaille sur une copie? Si tu fait ca, j;esepre que tu te creer un branche pour developpe dedans

Vu que generer l'images prend du temps, je te suggere de copiee diraectement l'image dans ton dossier /ip29/ilafores_group/projet_PROVID19/ILL_pipelines/containers/

`cp /project/def-ilafores/common/ILL_pipelines/containers/metawrap.1.3.sif /ip29/ilafores_group/projet_PROVID19/ILL_pipelines/containers/`

**Comment by jorondo1** [comment]
D'ac je comprends. J'ai copié parce que j'avais besoin de tester un nouveau paramètre sur Kraken. Je vais devoir intégrer ce paramètre au pipeline alors je vais en profiter pour me pratiquer à travailler avec une branch et faire un commit, j'ai pas encore fait tout le processus. On s'en reparle à notre meeting!
