### ISSUE TITLE
allsamples script invalid option

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#49]
Je teste ceci et j'obtiens l'erreur suivante
```
export PROVID=/nfs3_ib/ip29-ib/ip29/ilafores_group/projet_PROVID19
export ILL_PIPELINES=$PROVID/ILL_pipelines
export __EMAIL="ronj2303@usherbrooke.ca"
cd $PROVID
bash $ILL_PIPELINES/generateslurm_taxonomic_profile.allsamples.sh \
--kreports "${PROVID}/taxKB_conf01/*/*_bracken/*_S.kreport" \
--out $PROVID/taxKB_conf01 \
--bowtie_index_name provid_species \
--chocophlan_db /nfs3_ib/ip29-ib/ssdpool/shared/ilafores_group/humann_dbs/chocophlan \
--slurm_email $__EMAIL \
--slurm_threads 24 --slurm_mem 31G
load and valdiate env
/nfs3_ib/ip29-ib/ip29/ilafores_group/projet_PROVID19/ILL_pipelines/generateslurm_taxonomic_profile.allsamples.sh: line 15: source: --: invalid option
source: usage: source filename [arguments]
```
dans le script ligne 15 c'est $CONF_PARAMETERS je ne suis pas sûr ça fait référence à quoi?

**Comment by jflucier** [comment]
ton code est pas updater.....

git pull origin main dans ton repertoire /nfs3_ib/ip29-ib/ip29/ilafores_group/projet_PROVID19/ILL_pipelines/

ceci dit tu devrait travaille en utilisant le code de se repertoire pour tester.

/project/def-ilafores/common/ILL_pipelines

le seul temps que tu dois utilise ton propre repertoire selon moi est quand tu veux travaille sur une branche
