### ISSUE TITLE
metaWRAP kraken module

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#5]
dans metaWRAP, on pourrait utiliser le module kraken complet tel qu'utilisé dans humann, donc incluant Bracken avant KronaTools. La seule différence c'est qu'on aura pas besoin de créer une bugs-list custom.

On pourrait quand même intégrer le script pour créer la table complète de taxonomie en utilisant tous les samples?

**Comment by jflucier** [comment]
par termine de tester metawrap mais voici le pipleine, jai teste jusqua l'etape de reassembly (le reste en cours).

voir [ici](https://github.com/jflucier/ILL_pipelines/blob/main/metawrap_custom/run_pipeline.sh)

En resume, presentement les etapes sont comme suit:

1. kneaddata
2. metawrap assembly
3. metawrap binning with checkM
4. metawrap bin refinement
5. metawrap bin reassembly
6. metawrap bin classification
7. metawrap bin annotation

Selon mes tests sur un echantilllon le pipeline prendra environ 1-2 jours d'execution. L'etape binning tourne pendant 9h pour les tests que jai fait. En fait c'est une etape de checkM durant el binning qui ralenti le truc car ca roule a un seul thread car chaque thread bouffe env 40GB de ram selon la doc.

Tu aimerais donc que je modifie le pipeline comme suit:

1. kneaddata
2. kraken2
3. bracken pour tout les niveau de taxonomie
4. metawrap assembly
5. metawrap binning with checkM
6. metawrap bin refinement
7. metawrap bin reassembly
8. metawrap bin classification
9. metawrap bin annotation

C'est bien ca? Faut savoir que ceci va ajoute du temps d'execution a la job.

**Comment by jorondo1** [comment]
En fait, kraken/brakcen se passent sur les reads et les contigs, mais c'est indépendant des autres modules (sauf contigs qui requiert assembly avant).  C'est indépendant dans le sens que ça peut être fait en parallèle du reste, rien ne dépend de l'output kraken/bracken.

Je sais pas comment tu montes le config, mais est-ce qu'on pourra spécifier quels modules on veut faire rouler ? ou est-ce qu'on va manuellement partir chaque module?

on peut s'appeler pour jaser de la meilleure stratégie si tu veux

**Comment by jorondo1** [comment]
mon commentaire original voulait surtout dire qu'on a pas besoin de réécrire un nouveau script kraken/bracken, on peut réutiliser celui du pipeline humann

**Comment by jflucier** [comment]
plus simple de copie coller au script metawrap

pour etre certain, faudrait se parler direct avant de faire ce changement.

**Comment by jorondo1** [comment]
ok es-tu dispo lundi 13h ou mercredi am ?
