### ISSUE TITLE
output basename humann script

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#50]
j'essaie de rouler le script humann en mode nt seulement pour faire des tests (pas sur les noeuds)

est-ce qu'il y a une raison pourquoi le script a une variable $sample et une $__sample ? ça me cause un bug car humann demande un --output-basename ([ici](https://github.com/jflucier/ILL_pipelines/blob/b1c1ed4fa66c8f5cb37a3fb77f4336397033ea4a/scripts/functionnal_profile.humann.sh#L183)) et cette variable n',est pas définie dans ce script. 

Je suis en train de travailler sur une branche de ce script donc s'il faut remplacer tous les __sample par sample let me know je peux m'en occuper

**Comment by jflucier** [comment]
patch done

commit id [dfadba3](https://github.com/jflucier/ILL_pipelines/commit/dfadba3e6957f660c20750ffe9053fbe4d90bdbf)

**Comment by jorondo1** [comment]
cool merci, est-ce que je peux merge ça avec la branche sur laquelle je travaille en ce moment sans perdre mes modifs? C'est quoi la manière la plus efficace?

**Comment by jflucier** [comment]
assure toi d'etrte dans ta branche

```
$ git status
On branch ta_branche
....

```

ensuite:

`git merge main`

jai rarement fait ce chemin inverse.... ca devrait etre bon.
