### ISSUE TITLE
assembly repair.sh semble produire un fichier vide

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#51]
je teste l'assemblage sur un autre jeu d'échantillons et j'ai une erreur étrange comme si un des deux fastq était vide après le reordering du script assembly ([ici](https://github.com/jflucier/ILL_pipelines/blob/ba0fd0bc9782e224899782d17fbe157a75e9ec6b/scripts/assembly.metawrap.sh#L152) d'après moi).

Voir le log sur `/nfs3_ib/ip29-ib/ip29/ilafores_group/jo/Plachokova2021/assembly/logs/assembly_bin_refinement-104195_1.slurm.out
`

**Comment by jflucier** [comment]
je check ca bientot

**Comment by jflucier** [comment]
as-tu reussi a faire fonctionne le repair en fin du compte?

**Comment by jflucier** [comment]
@jorondo1 

peux tu me confimer si le bug persiste depuis les 2000 release que jai effectue

merci

**Comment by jflucier** [comment]
oubli ca... jai enlever l'utilisation de bbmap. Je diagnostique directement a partir des headers.
