### ISSUE TITLE
sourmash code pas up to date sur mp2?

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#52]
je crois que mp2 n'a pas laa dernière version de ce code. J'essaie de debugger qqch mais je réalise par exemple que [cette ligne ](https://github.com/jflucier/ILL_pipelines/blob/ba0fd0bc9782e224899782d17fbe157a75e9ec6b/generateslurm_sourmash.sh#L13) n'est pas la même que dans /project/def-ilafores/common/ILL_pipelines/generateslurm_sourmash.sh (où le path finit par /SM_db)

la bonne version est celle sur le repo

**Comment by jflucier** [comment]
je check ca bientot

va falloir migrer vers le nouveau serveur de bio. On a acces a un container avec 800G ram et 92 cpu

**Comment by jflucier** [comment]
done

**Comment by jflucier** [comment]
le code reste pareil mis a part quil faudrait change quelques valeurs defini par defaut je crois

c'est les dependance comme les soft et environment quil va falloir reinstaller.

de ton cote ca implique rien. Je vais m'occupe de ca

Je te dirai lorsque c fait
