### ISSUE TITLE
Installation GTDB-Tk

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#53]
On utiliserait le classify_wf avec l'option --full-tree tant qu'à avoir du RAM à revendre.

On pourrait optimiser en skippant le gene calling avec l'option --gene puisqu'on va le faire avec Prodigal (via MicrobeAnnotator)

Y'a aussi des options d'optimisation qui pourraient t'intéresser https://ecogenomics.github.io/GTDBTk/commands/classify_wf.html#

**Comment by jflucier** [comment]
sur ip34.ccs.usherbrooke.ca. Voici comment appeler gtdbtk:

```
newgrp def-ilafores
# call gtdbtk
singularity exec -e \
--env GTDBTK_DATA_PATH=/fast/def-ilafores/GTDB/release207_v2 \
-B /home:/home \
-B /fast:/fast \
/home/def-ilafores/programs/ILL_pipelines/containers/gtdbtk.sif \
gtdbtk classify_wf -h

```

reste a faire les wrapper scripts pour la soumission slurm.

je reping des que c'est pait
