### ISSUE TITLE
cannot stat kneaddata container

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#58]
[Cette ligne](https://github.com/jflucier/ILL_pipelines/blob/230d57bfe7da2a152c101f754d05802507875e3a/scripts/preprocess.kneaddata.sh#L118) ne pointe pas au container, je pense qu'il manque /programs/ entre ../ et /containers

**Comment by jflucier** [comment]
je vais essayer de corriger ca mais en attendant tu dois caller le script avec le fullpath.

`bash $ILL_PIPELINES/generateslurm_preprocess.kneaddata.sh ...`
