### ISSUE TITLE
single quote drep regex file path

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#59]
il faut spécifier que le path regex pour drep doit être single quote, sinon seulement le 1er génome est lu

**Comment by jflucier** [comment]
tu veux dire quand tu passe en parametre au script? C'est un requis bash.

je peux ajouter a la doc

**Comment by jorondo1** [comment]
non je voulais dire, en single quote plutôt qu'en double quotes!
scuse c'était pas clair

**Comment by jflucier** [comment]
updater la doc a plusierus endroits

voir [https://github.com/jflucier/ILL_pipelines#bin-dereplication](https://github.com/jflucier/ILL_pipelines#bin-dereplication)
