### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#6]
dans HOW TO RUN 
```
cp ${HUMANN_CUSTOM_INSTALL}/my.example.config .
cp ${HUMANN_CUSTOM_INSTALL}/buglist.sample.test.tsv .
cp ${HUMANN_CUSTOM_INSTALL}/humann.sample.tsv .
vi my_analysis.config
```
la dernière ligne ne devrait pas être 
`vi my.example.config` ?

aussi, est-ce qu'il y a un avantage à utiliser vi plutôt que nano pour editer des fichiers dans terminal?

**Comment by jflucier** [comment]
good catch.

je vais changer.

Vi ou nano c bon.
