### ISSUE TITLE
assembly: certains samples ne démarrent pas sur les noeuds

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#61]
Je relaunch l'assembly pour moss (pas en co-assembly cette fois) et plusieurs samples ne démarrent même pas sur les noeuds; ex. pour les array 1 et 2, et 34-140 je n'ai même pas de log généré. J'ai ajouté l'ouptput d'erreur #SBATCH -e ..slurm.err et rien n'est généré non plus. As-tu une idée qu'est-ce qui pourrait causer un problème comme ça? difficile sans traces d'erreur...

`sbatch --array=1-140 /net/nfs-ip34/home/def-ilafores/analysis/boreal_moss/assembly/assembly_bin_refinement.metawrap.slurm.sh`

Quand je roule le de ce script (la commande metawrap) ça fonctionne, mais je pense que ça ne se rend même pas là sur les noeuds parce qu'aucun log n'est généré pour ces arrays.

**Comment by jflucier** [comment]
tu semble avoir des jobs qui tourbne en ce moment et les log se peulple on dirait

ce ticket est toujour valide?

**Comment by jflucier** [comment]
ok je comprend... juste certaines jobs plantent

**Comment by jorondo1** [comment]
génial merci !!
