### ISSUE TITLE
erreur annotation pipeline

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#62]
J'ai essayé de rouler 
` bash $ILL_PIPELINES/scripts/annotate_bins.sh -o assembly_60_taxonomy -drep assembly_60_bins/drep_genomes/dereplicated_genomes
`
Prokka fonctionne, mais après microbeannotator plante:
```
real    32m55.563s
user    250m4.749s
sys     43m46.025s
bind_path=/temp
ma_db_bind=/cvmfs
out_bind=/
Will run microbeannotator using 12 precoesses and 2 threads
WARNING: skipping mount of /temp: stat /temp: no such file or directory
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
FATAL:   container creation failed: mount hook function failure: mount /temp->/temp error: while mounting /temp: mount source /temp doesn't exist
```

Pour l'instant j'ai vraiment juste besoin de rouler gtdb-tk, je vais fouiller dans le code pour la commande, mais je voulais t'aviser quand même

**Comment by jorondo1** [comment]
oublie ça j'ai réussi ! mes tmp folder étaient mal définis. J'ai aussi réussi à rouler mash standalone.

**Comment by jflucier** [comment]
PTI, l'option -B de singularity defini des bind path entre le serveur et le container singularity, donc tu dois ajouter un bind path pour que ca marche:

```
singularity exec --writable-tmpfs -e \
--env GTDBTK_DATA_PATH=$gtdb_db \
-B $gtdb_db:$gtdb_db \
-B /nfs3_ib/nfs-ip34/home/def-ilafores:/nfs3_ib/nfs-ip34/home/def-ilafores \
-B $PARENT_DIR:$PARENT_DIR \
-e /nfs3_ib/nfs-ip34/home/def-ilafores/programs/ILL_pipelines/containers/gtdbtk.2.2.5.sif \
gtdbtk classify_wf --cpus 32 \
--genome_dir $PARENT_DIR/assembly_60_bins/drep_genomes/dereplicated_genomes \
--out_dir $PARENT_DIR/assembly_60_gtdbtk \
--mash_db $gtdb_db \
--extension fa
```

compredn pas trop ton truc de mash vs gtdbtk. On va modifier le pipeline d'annotation de bin?
