### ISSUE TITLE
GUNC

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#67]
Dans le pipeline d'assemblage du EBI on utilisait cet outil pour détecter les bins chimériques ou contaminés. Est-ce que tu pourrais m'installer ça? https://github.com/grp-bork/gunc

La commande ressemblerait à ça:
`gunc run -t 4 -i ${bin_fa} --db_file gunc_db_2.0.4.dmnd -o ${bin_fa}_gunc`

**Comment by jflucier** [comment]
quel bd tu veux?

Which db to download. progenomes,gtdb Default: progenomes

**Comment by jorondo1** [comment]
progenomes

**Comment by jflucier** [comment]
done

pour utiliser faire ceci:

```
module load apptainer
singularity exec -e /home/def-ilafores/programs/gunc_1.0.5.sif gunc run ...

```
jai telecharge la bd dans /fast/def-ilafores/gunc_db/

enjoy!

**Comment by jorondo1** [comment]
sic merci beaucoup!
