### ISSUE TITLE
lets make the custom db smaller...!

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#9]
Avec notre code actuel, la bugs_list crée une db qui représente plus de la moitié de la full chocophlan. Je pense qu'on perd du temps à indexer une si grosse proportion de la db, sans gagner grand chose; Tant qu'à indexer 7500 des 11000 génomes de la db, aussi ben utiliser la full.

Je créerais une custom db avec seulement le top X% des bugs de chaque samples comme input pour la liste finale (ça devrait nous créer une liste totale de quelques centaines de bugs, vs 7400 si on prend tout).

Après si qqun veut vraiment associer un max d'info taxonomique à ses gènes, il aura juste à run sur la full chocophlan. Ça nous ferait un mode quick et un mode lent.

On peut remplacer [ces 4 lignes](https://github.com/jflucier/ILL_pipelines/blob/6d36038463b4b22cc0160808beb3973c688df789/humann_custom/01_make_custom_buglist_input.sh#L144) par : 

```
top_bugs=`wc -l temp.MPA.TXT | awk '{print $1}'`
grep "|s" temp.MPA.TXT | sort -k 2 -r -n - | head -n $((top_bugs / 50)) - `#selects top 2 percent bugs`\
	| awk '{printf("%s\t\n", $0)}' - | awk 'BEGIN{printf("#mpa_v30_CHOCOPhlAn_201901\n")}1' - \
        > $__EXP_DIR/${__EXP_NAME}-bugs_list.MPA.TXT
```

éventuellement faudrait voir comment on pourrait skipper le subsetting des bugs via le config si le user veut faire la full run (donc skip tout ce qui est bugs_list et utilise la full chocophlan pour l'étape de nt alignment)

et comment spécifier un % (eg. 2) dans le config et réussir à faire l'opération $((top_bugs * percentage)) que j'arrive pas à trouver

comme ça si quelqu'un veut faire une run extra fast pourrait mettons utiliser la kraken_16gb et mettre un petit pourcentage pour rendre la custom db creation plus light sans trop perdre d'info pertinente

**Comment by jflucier** [comment]
si tu met le pourcentage a 100% c pas equivalent a full choco? Ca devrait etre presque = si je comprend bien ton point initial.

**Comment by jorondo1** [comment]
non 100% voudrait dire créer une db custom avec tous les bugs trouvés, même ceux pour qui kraken n'a aligné qu'une seule séquence

la full choco c'est en utilisant --bypass-prescreen qu'on l'utiliserait; l'alignement se fera sur toute la database, ce qui nous permet de complètement skip la création d'une nouvelle db

le point est surtout que c'est tellement long à créer, que tant qu'à en faire une qui représente >50% de la full db, aussi bien pas en faire

je sais pas si c'est clair ?

**Comment by jorondo1** [comment]
oui en effet faudrait créer un index complet une fois pour toutes si on veut utiliser la full_chocophlan

mon commentaire que tu cites veut dire que dans ce cas, on pourra skip la création de la bugs list. Est-ce que tout ce qu'On a à faire c'est skip les scripts 01 et 02 ?

**Comment by jflucier** [comment]
> mon commentaire que tu cites veut dire que dans ce cas, on pourra skip la création de la bugs list. Est-ce que tout ce qu'On a à faire c'est skip les scripts 01 et 02 ?

exactement! u par s le script 03 et tu pointe sur le nt_db de ton choix

**Comment by jflucier** [comment]
je met ca ou exactement?

**Comment by jorondo1** [comment]
Dans ce dossier là, un subdir boreal_moss mettons? Juste pour qu'elle soit sur le SSD ou ça sert à rien?

**Comment by jflucier** [comment]
ou est le boreal_moss?

`
|12:32:03|jflucier@ip29:[ILL_pipelines]> ls /nfs3_ib/ip29-ib/ssdpool/shared/ilafores_group/humann_dbs/
chocophlan
|12:32:05|jflucier@ip29:[ILL_pipelines]>

`

**Comment by jorondo1** [comment]
je suis pas sûr qu'on se comprend

est-ce que l'index de la custom database que tu avais indexée il y a quelques semaines (qui a pris genre 4 jours à monter) peut/doit se retrouver dans le ssd ? est-ce celle-ci : /project/def-ilafores/common/humann3/lib/python3.7/site-packages/humann/data/boreal_moss

**Comment by jflucier** [comment]
ouin je sais plus trop quelleest la bonne. Dans le dossier, il y a le fichier *.MPA.TXT qui a ete utilise pour genere la bd et l'index bowtie

```
|14:05:28|jflucier@ip29:[ILL_pipelines]> wc -l /project/def-ilafores/common/humann3/lib/python3.7/site-packages/humann/data/custom_chocophlan/moss-bugs_list.MPA.TXT 
4372 /project/def-ilafores/common/humann3/lib/python3.7/site-packages/humann/data/custom_chocophlan/moss-bugs_list.MPA.TXT
|14:24:46|jflucier@ip29:[ILL_pipelines]> wc -l /project/def-ilafores/common/humann3/lib/python3.7/site-packages/humann/data/boreal_moss/boreal_moss-bugs_list.MPA.TXT 
7428 /project/def-ilafores/common/humann3/lib/python3.7/site-packages/humann/data/boreal_moss/boreal_moss-bugs_list.MPA.TXT

```

la bd boreal_moss contiens 7428 entrees alors que la bd custom_chocophlan contiens 4372 entrees

je soupconne que la bonne est boreal_moss: /project/def-ilafores/common/humann3/lib/python3.7/site-packages/humann/data/boreal_moss/boreal_moss-bugs_list.MPA.TXT

peux-tu me confirmer stp et je pars le transfert vers le ssd.

JF

**Comment by jorondo1** [comment]
oui c'est bien elle !
tu peux transférer tout le dir

**Comment by jflucier** [comment]
transfert termine vers /ssdpool/shared/ilafores_group/humann_dbs/
